#speaker:Anxious Student   #portrait:Anxious #layout:OverWorld #voiceover:default
Hmmm...
#speaker:Anxious Student   #portrait:Anxious #layout:OverWorld #voiceover:default
Hmmm...
#speaker:Anxious Student  #portrait:Anxious #layout:OverWorld #voiceover:default
Oh! I didn't see you there.
#speaker:Anxious Student  #portrait:Anxious #layout:OverWorld #voiceover:default
Hmmm...